llm:
  default_provider: local_openai
  # log_dir: .semduck/llm-logs
  # To use different models for planning and result summarization, define both tasks:
  # Note that ask_plan requires a model that supports tools, ask_summary can use a 
  # smaller model that doesn't support tools.
  # tasks:
  #   ask_plan:
  #     provider: local_openai
  #     model: qwen2.5-coder
  #   ask_summary:
  #     provider: local_openai
  #     model: qwen2.5-coder
  providers:
    local_openai:
      type: openai_compatible
      model: qwen2.5-coder
      base_url: http://localhost:8000/v1
