name: semduck_integration
version: 0.1.0
config-version: 2
profile: semduck_integration

model-paths:
  - models
seed-paths:
  - seeds

on-run-start:
  - "{{ dbt_semduck.semduck_on_run_start() }}"

models:
  semduck_integration:
    +materialized: table
